import type { Metadata } from 'next';
import Link from 'next/link';
import { supabaseServer } from '@/lib/supabase/server';
import DesignGallery from '@/components/DesignGallery';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import EzoicPlacements from '@/components/EzoicPlacements';
import CategoryFilterBar from '@/components/CategoryFilterBar';
import { getPlacementIds } from '@/lib/ezoic';
import { withDesignSlugs } from '@/lib/slug';
import { createPageMetadata } from '@/lib/seo';

export const revalidate = 0;

export async function generateMetadata(): Promise<Metadata> {
  const { count } = await supabaseServer
    .from('designs')
    .select('id', { count: 'exact', head: true })
    .eq('status', 'published');

  const totalDesigns = count ?? 0;
  const description = totalDesigns > 0
    ? `Browse ${totalDesigns}+ production-ready AI-generated web designs spanning landing pages, dashboards, and e-commerce flows.`
    : 'Browse production-ready AI-generated web designs spanning landing pages, dashboards, and e-commerce flows.';

  return createPageMetadata({
    title: 'AI design inspiration for modern engineering teams',
    description,
    path: '/',
  });
}

export default async function HomePage({
  searchParams,
}: {
  searchParams: { category?: string };
}) {
  const category = searchParams?.category;
  const placementIds = getPlacementIds();

  let query = supabaseServer
    .from('designs')
    .select('*')
    .eq('status', 'published')
    .order('created_at', { ascending: false })
    .range(0, 11);

  if (category) {
    query = query.eq('category', category);
  }

  const { data: initialDesigns } = await query;
  const designsWithSlugs = initialDesigns ? withDesignSlugs(initialDesigns) : [];

  return (
    <div className="min-h-screen bg-luxury-white">
      <Header />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <section className="mb-8 space-y-6 text-center md:text-left">
          <p className="text-xs uppercase tracking-[0.35em] text-gray-500">
            United States · AI Product Design
          </p>
          <h1 className="text-4xl md:text-5xl font-semibold text-gray-900 tracking-tight">
            Production-ready AI web design inspiration for modern engineering teams
          </h1>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto md:mx-0">
            UI Syntax curates Silicon Valley standard landing pages, dashboards, and e-commerce layouts
            generated by AI. Every concept is reviewed with accessibility guidelines, marketing copy, and developer
            handoff in mind so your next release ships faster—complete with copy-ready HTML and auto-generated React
            code on every design detail page.
          </p>
          <div className="flex flex-wrap justify-center md:justify-start gap-3">
            {["B2B SaaS", "Developer tools", "Fintech", "Commerce"].map((tag) => (
              <span
                key={tag}
                className="rounded-full border border-gray-900 px-4 py-1 text-sm font-medium text-gray-800 bg-white"
              >
                {tag}
              </span>
            ))}
          </div>
        </section>

        <section className="mb-12 rounded-3xl border border-gray-200 bg-white/90 p-6 sm:p-8 text-gray-700 shadow-sm">
          <h2 className="text-2xl font-semibold text-gray-900">What you will find inside UI Syntax</h2>
          <p className="mt-4 text-base leading-relaxed">
            UI Syntax is a curated library of AI-generated web layouts built for teams that ship fast. Each design is
            reviewed for hierarchy, accessibility, and conversion-ready copy so product and engineering teams can move
            from inspiration to implementation without guesswork.
          </p>
          <p className="mt-4 text-base leading-relaxed">
            Browse by category, open a detail page, and copy the HTML or React code to jump-start your next release. The
            collection is continuously updated with layouts for modern SaaS, fintech, e-commerce, and developer tools.
          </p>
          <ul className="mt-5 space-y-2 text-sm text-gray-600">
            <li>Production-grade landing pages with proven hero, social proof, and pricing patterns.</li>
            <li>Dashboard and admin templates that prioritize clarity, density, and fast scanning.</li>
            <li>Component-focused references for cards, navs, and CTA sections you can reuse.</li>
          </ul>
        </section>

        <section className="mb-12">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div>
              <p className="text-xs uppercase tracking-[0.35em] text-gray-500">Top Playbooks</p>
              <h2 className="mt-2 text-3xl font-semibold text-gray-900">Strategic playbooks teams revisit</h2>
              <p className="mt-3 text-sm text-gray-600 max-w-2xl">
                Jump straight into the highest-signal playbooks for SaaS landing pages, dashboards, commerce, and UX
                psychology.
              </p>
            </div>
            <Link
              href="/playbooks"
              className="text-xs uppercase tracking-[0.3em] text-gray-600 hover:text-gray-900"
            >
              View all playbooks
            </Link>
          </div>
          <div className="mt-6 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {[
              {
                title: 'SaaS Landing Page UX Strategy',
                href: '/playbooks/saas-landing-page-ux',
                description: 'Value props, social proof systems, and CTA ladders built for B2B SaaS teams.',
              },
              {
                title: 'Dashboard UX Design Principles',
                href: '/playbooks/dashboard-ux-principles',
                description: 'Density control, hierarchy, and dark mode tokens for analytics-heavy products.',
              },
              {
                title: 'E-Commerce UI Conversion Patterns',
                href: '/playbooks/ecommerce-conversion-patterns',
                description: 'Conversion-ready flows from PDP to checkout with trust and urgency baked in.',
              },
              {
                title: 'UX Psychology in Modern Interfaces',
                href: '/playbooks/ux-psychology',
                description: 'Behavioral triggers and messaging patterns that guide attention and decisions.',
              },
              {
                title: 'UI Optimization for Core Web Vitals',
                href: '/playbooks/ui-core-web-vitals',
                description: 'Performance guardrails for LCP, CLS, and INP at the design system level.',
              },
            ].map((playbook) => (
              <Link
                key={playbook.href}
                href={playbook.href}
                className="group rounded-3xl border border-gray-200 bg-white/90 p-6 shadow-sm transition hover:-translate-y-1 hover:border-gray-900"
              >
                <p className="text-xs uppercase tracking-[0.3em] text-gray-500">Playbook</p>
                <h3 className="mt-3 text-xl font-semibold text-gray-900 group-hover:text-gray-700">
                  {playbook.title}
                </h3>
                <p className="mt-3 text-sm text-gray-600 leading-relaxed">{playbook.description}</p>
              </Link>
            ))}
          </div>
        </section>

        <section className="mb-12">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div>
              <p className="text-xs uppercase tracking-[0.35em] text-gray-500">Top Collections</p>
              <h2 className="mt-2 text-3xl font-semibold text-gray-900">Curated collections in focus</h2>
              <p className="mt-3 text-sm text-gray-600 max-w-2xl">
                Design sets grouped by strategic themes so you can scan patterns quickly.
              </p>
            </div>
            <Link
              href="/collections"
              className="text-xs uppercase tracking-[0.3em] text-gray-600 hover:text-gray-900"
            >
              View all collections
            </Link>
          </div>
          <div className="mt-6 grid gap-6 md:grid-cols-2">
            {[
              {
                title: 'Best SaaS Landing Pages',
                href: '/collections/best-saas-landing-pages',
                description: 'Conversion-grade hero, pricing, and proof layouts curated for SaaS teams.',
              },
              {
                title: 'Minimalist Dashboards',
                href: '/collections/minimalist-dashboards',
                description: 'Signal-first dashboards that balance density, clarity, and dark mode.',
              },
            ].map((collection) => (
              <Link
                key={collection.href}
                href={collection.href}
                className="group rounded-3xl border border-gray-200 bg-white/90 p-6 shadow-sm transition hover:-translate-y-1 hover:border-gray-900"
              >
                <p className="text-xs uppercase tracking-[0.3em] text-gray-500">Collection</p>
                <h3 className="mt-3 text-xl font-semibold text-gray-900 group-hover:text-gray-700">
                  {collection.title}
                </h3>
                <p className="mt-3 text-sm text-gray-600 leading-relaxed">{collection.description}</p>
              </Link>
            ))}
          </div>
        </section>

        <section className="mb-12 rounded-3xl border border-gray-200 bg-white/90 p-8 shadow-sm">
          <p className="text-xs uppercase tracking-[0.35em] text-gray-500">What is UI Syntax?</p>
          <h2 className="mt-2 text-3xl font-semibold text-gray-900">A strategic design library for modern product teams</h2>
          <div className="mt-4 space-y-4 text-sm sm:text-base text-gray-700 leading-relaxed">
            <p>
              UI Syntax is a curated library of production-ready AI web design references built for teams that need to
              move quickly from strategy to shipped UI. Every layout is reviewed for hierarchy, copy clarity, and
              implementation feasibility so designers and engineers can reuse patterns without rethinking the basics.
            </p>
            <p>
              Start with the Playbooks to understand the strategy behind each interface type, then open Collections to
              see how those principles translate into real layouts. The combination helps teams align messaging,
              interaction design, and performance standards in one pass.
            </p>
            <p>
              Browse the gallery for ready-to-ship patterns, then jump to the related Playbook or Collection when you
              need deeper context. This cross-linking is designed for both human readers and AI systems that summarize
              design intent.
            </p>
          </div>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link
              href="/playbooks"
              className="inline-flex items-center rounded-full border border-gray-900 px-4 py-2 text-xs font-semibold uppercase tracking-[0.3em] text-gray-900 transition hover:bg-gray-900 hover:text-white"
            >
              Explore Playbooks
            </Link>
            <Link
              href="/collections"
              className="inline-flex items-center rounded-full border border-gray-200 px-4 py-2 text-xs font-semibold uppercase tracking-[0.3em] text-gray-700 transition hover:border-gray-900 hover:text-gray-900"
            >
              Browse Collections
            </Link>
          </div>
        </section>

        <CategoryFilterBar selectedCategory={category || null} className="mb-12" />

        <DesignGallery initialDesigns={designsWithSlugs} initialCategory={category || null} />

        {placementIds.length > 0 && (
          <EzoicPlacements placementIds={placementIds} wrapperClassName="my-24 space-y-12" />
        )}
      </main>

      <Footer />
    </div>
  );
}
