import { supabaseServer } from '@/lib/supabase/server';
import DesignGallery from '@/components/DesignGallery';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import EzoicPlacements from '@/components/EzoicPlacements';
import CategoryFilterBar from '@/components/CategoryFilterBar';
import { getPlacementIds } from '@/lib/ezoic';
import { withDesignSlugs } from '@/lib/slug';

export const revalidate = 0;

export default async function HomePage({
  searchParams,
}: {
  searchParams: { category?: string };
}) {
  const category = searchParams?.category;
  const placementIds = getPlacementIds();

  let query = supabaseServer
    .from('designs')
    .select('*')
    .eq('status', 'published')
    .order('created_at', { ascending: false })
    .range(0, 11);

  if (category) {
    query = query.eq('category', category);
  }

  const { data: initialDesigns } = await query;
  const designsWithSlugs = initialDesigns ? withDesignSlugs(initialDesigns) : [];

  return (
    <div className="min-h-screen bg-luxury-white">
      <Header />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <section className="mb-8 space-y-6 text-center md:text-left">
          <p className="text-xs uppercase tracking-[0.35em] text-gray-500">
            United States · AI Product Design
          </p>
          <h1 className="text-4xl md:text-5xl font-semibold text-gray-900 tracking-tight">
            Production-ready AI web design inspiration for modern engineering teams
          </h1>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto md:mx-0">
            UI Syntax curates Silicon Valley standard landing pages, dashboards, and e-commerce layouts
            generated by AI. Every concept is reviewed with accessibility guidelines, marketing copy, and developer
            handoff in mind so your next release ships faster—complete with copy-ready HTML and auto-generated React
            code on every design detail page.
          </p>
          <div className="flex flex-wrap justify-center md:justify-start gap-3">
            {["B2B SaaS", "Developer tools", "Fintech", "Commerce"].map((tag) => (
              <span
                key={tag}
                className="rounded-full border border-gray-900 px-4 py-1 text-sm font-medium text-gray-800 bg-white"
              >
                {tag}
              </span>
            ))}
          </div>
        </section>

        <section className="mb-12 rounded-3xl border border-gray-200 bg-white/90 p-6 sm:p-8 text-gray-700 shadow-sm">
          <h2 className="text-2xl font-semibold text-gray-900">What you will find inside UI Syntax</h2>
          <p className="mt-4 text-base leading-relaxed">
            UI Syntax is a curated library of AI-generated web layouts built for teams that ship fast. Each design is
            reviewed for hierarchy, accessibility, and conversion-ready copy so product and engineering teams can move
            from inspiration to implementation without guesswork.
          </p>
          <p className="mt-4 text-base leading-relaxed">
            Browse by category, open a detail page, and copy the HTML or React code to jump-start your next release. The
            collection is continuously updated with layouts for modern SaaS, fintech, e-commerce, and developer tools.
          </p>
          <ul className="mt-5 space-y-2 text-sm text-gray-600">
            <li>Production-grade landing pages with proven hero, social proof, and pricing patterns.</li>
            <li>Dashboard and admin templates that prioritize clarity, density, and fast scanning.</li>
            <li>Component-focused references for cards, navs, and CTA sections you can reuse.</li>
          </ul>
        </section>

        <CategoryFilterBar selectedCategory={category || null} className="mb-12" />

        <DesignGallery initialDesigns={designsWithSlugs} initialCategory={category || null} />

        {placementIds.length > 0 && (
          <EzoicPlacements placementIds={placementIds} wrapperClassName="my-24 space-y-12" />
        )}
      </main>

      <Footer />
    </div>
  );
}
